<?php

namespace App\Http\Requests\Cart;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\Exceptions\HttpResponseException;
class CartStoreRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'products'=>'required|array',
            'products.*.id'=>'required|exists:product_variations,id',
            'products.*.quantity'=>'numeric|min:1'
        ];
    }

    public function failedValidation(Validator $validator)
    {
        //parent::failedValidation($validator); // TODO: Change the autogenerated stub
        throw new HttpResponseException(response()->json($validator->errors())) ;
    }
}
