<?php

namespace App\Models;

use App\Models\Traits\HasPrice;
use App\Models\Traits\WithScopes;
use Illuminate\Database\Eloquent\Model;


class Product extends Model
{
    //
    use WithScopes,HasPrice ;
    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }

    public function stokeCount(){
        return $this->variations->sum(function ($variations){
            return $variations->stokeCount() ;
//            dd($variations->stokeCount());
        });
    }

    public function inStock(){
        return $this->stokeCount() > 0 ;
    }

    /*
     * here we will change the data that comming form database before send it to use
     */


    public function categories(){
        return $this->belongsToMany(Category::class) ;
    }

    public function variations(){
        return $this->hasMany(ProductVariation::class)->orderBy('order','asc');
    }
}
